### ISSUE TITLE
Зачем ices, если бог дал тебе liquidsoap?

### ISSUE THREAD

**Issue by yharahuts** [Nakilon/ytblpka#1]

**Comment by Nakilon** [comment]
Спасибо, не знал о таком.
Но весь этот список фич https://www.liquidsoap.info/doc-1.3.5/ мне не был нужен.

**Comment by yharahuts** [comment]
Там как минимум удобный шаффл плейлиста (да и вообще плейлисты), всякие кросфейд-переходы и нормализация звука из коробки, так что даже для потребностей уровня «чтобы файлики играло» мыло, кмк, намного круче чем ices.
